name: SimpleBucketMobs
version: '${project.version}'
main: adhdmc.simplebucketmobs.SimpleBucketMobs
api-version: 1.19
authors: [ Rhythmic, Peashooter101 ]
description: Shove your mobs into buckets like Axolotls! :D
